### ISSUE TITLE
Problem with the option 'Merge all links to singe page' and WuxiaWorld

### ISSUE THREAD

**Issue by SakenZeiner** [gmathi/NovelLibrary#165] opened 2021-02-08 16:49 UTC
If you have the 'Merge all link to single page' option enabled in Reader mode and then open up any chapter from WuxiaWorld, it's prequel and sequel chapters also open up, provided, they exist in the first place.

For example, if you open chapter 1300 of Overgeared in reader mode, after the chapter ends, it should ideally end scrolling but it continues with chapter 1299 and then chapter 1301 and then the chapter ends.

The option of merging all links merges entire prequel and sequel chapters in the same chapter and I think that option wasn't intended to work like that.

Edit: Last tried on 0.17

**Comment by gmathi** [comment] 2021-04-23 20:10
I am unable to reproduce this in 0.18.4 (might have been fixed without looking here)

**Comment by gmathi** [comment] 2021-04-23 20:11
Let me know if this is still happening, I will re-open this.

**Closed by gmathi** 2021-04-23 20:10 UTC
Labels: 0.17, bug
